server:
  port: 8081
  servlet:
    context-path: /wildx
spring:
  application:
    name: wildx-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf63p54fld8f6f2ze6o.mysql.rds.aliyuncs.com:3306/wildx?useSSL=false
    username: wildx_wuchangwei88
    password: Wildx_wuchangwei88
  jackson:
      default-property-inclusion: non_null #如果序列化时属性为空，则忽略此属性

jwt:
  key: 王波大傻子

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka #注册拉取服务地址

mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null #插入策略，属性为空则不写入SQL
      update-strategy: not_null #修改策略，属性为空则不写入SQL语句中
      id-type: auto  #全局主键策略，默认为自增长
  type-aliases-package: xyz.wildx.entity #别名，扫包

logging:
  level:
    xyz.wildx: debug
